# See https://pre-commit.com for more information
repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File maintenance
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']

      # Safety checks
      - id: check-merge-conflict
      - id: debug-statements

      # File format validation
      - id: check-yaml
      - id: check-toml
      - id: check-json

      # Security and cleanup
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-docstring-first

  # Black formatter
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  # Ruff linter (fast Python linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format

  # MyPy type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--no-strict-optional']
        additional_dependencies:
          - types-PyYAML
          - types-toml
          - pydantic
        exclude: ^tests/
