# Base configuration for all experiments
# This file contains common settings that are inherited by all experiments

base:
  # API key from environment variable
  api_key: ${OPENAI_API_KEY}
  
  # Output directory for results
  output_dir: outputs
  
  # Cache directory for datasets
  cache_dir: .cache
  
  # Logging configuration
  log_level: INFO
  log_file: logs/experiment.log
  
  # Reproducibility
  random_seed: 42
  
  # API settings
  max_retries: 3
  timeout: 60

# Default model configuration
model:
  model_type: gpt-5
  # Temperature is fixed at 1.0 for GPT-5
  # temperature: 1.0

# Default benchmark configuration  
benchmark:
  metrics:
    - accuracy
    - f1_score
  shuffle: true
  
# Default strategy
strategy:
  strategy_type: baseline
