# Logging Configuration for Cosmos Coherence

development:
  version: 1
  disable_existing_loggers: false
  level: DEBUG

  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

    detailed:
      format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(funcName)s() - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: "%(asctime)s %(name)s %(levelname)s %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: detailed
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: ./logs/cosmos_coherence.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: utf8

    error_file:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: detailed
      filename: ./logs/errors.log
      maxBytes: 10485760  # 10MB
      backupCount: 5
      encoding: utf8

  loggers:
    cosmos_coherence:
      level: DEBUG
      handlers: [console, file, error_file]
      propagate: false

    uvicorn.access:
      level: INFO
      handlers: [console]
      propagate: false

    uvicorn.error:
      level: INFO
      handlers: [console, error_file]
      propagate: false

  root:
    level: INFO
    handlers: [console, file]

production:
  version: 1
  disable_existing_loggers: false
  level: WARNING

  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

    json:
      class: pythonjsonlogger.jsonlogger.JsonFormatter
      format: "%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d"

  handlers:
    console:
      class: logging.StreamHandler
      level: WARNING
      formatter: json
      stream: ext://sys.stdout

    file:
      class: logging.handlers.RotatingFileHandler
      level: WARNING
      formatter: json
      filename: /var/log/cosmos_coherence/app.log
      maxBytes: 52428800  # 50MB
      backupCount: 10
      encoding: utf8

    error_file:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: json
      filename: /var/log/cosmos_coherence/errors.log
      maxBytes: 52428800  # 50MB
      backupCount: 10
      encoding: utf8

    syslog:
      class: logging.handlers.SysLogHandler
      level: ERROR
      formatter: json
      address: /dev/log
      facility: local0

  loggers:
    cosmos_coherence:
      level: WARNING
      handlers: [console, file, error_file, syslog]
      propagate: false

    uvicorn.access:
      level: WARNING
      handlers: [file]
      propagate: false

    uvicorn.error:
      level: ERROR
      handlers: [console, error_file, syslog]
      propagate: false

  root:
    level: ERROR
    handlers: [console, file]

testing:
  version: 1
  disable_existing_loggers: false
  level: DEBUG

  formatters:
    default:
      format: "%(levelname)s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout

  root:
    level: DEBUG
    handlers: [console]
